title: Welcome to Flexton
description: Flexton is a responsive and ultra-minimal theme for Jekyll.
baseurl: "" # the subpath of your site, e.g. /blog
url: "honggibeom.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name: GI BEOM HONG
author-image: 1.jpg
author-job: Web Developer
author-email: hkb8129@gmail.com # Add your email for contant form.
author-github: honggibeom # Add your twitter account
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning.

# Social settings
social-twitter: honggibeom
social-facebook:
social-github: honggibeom
social-instagram:

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
